## set to true to allow sending titles when died,else it didnt shown

send_title: true

## edit the title and subtitle message here

title: "§l§cYou Died"
subtitle: "§7Better luck next time!"

## thank you for using my plugin :)
